apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ZONE: "default"
  LOG_FORMAT: "json"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "fraud_detection_db"
  REDIS_URL: "redis://redis:6379/0"
  KAFKA_BOOTSTRAP_SERVERS: "redpanda:9092"
  SCORING_URL: "http://scoring-service:8001"
  BACKOFFICE_URL: "http://backoffice-api:8003"
  SMTP_HOST: "smtp-relay"
  SMTP_PORT: "25"
  CORS_ORIGINS: "https://fraude.local"
